---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: kino
description: Personal Fedora Silverblue image with NVIDIA open drivers, ASUS tools, and virtualization support.

# Includes matching NVIDIA open kernel modules, CUDA libraries, and container tools.
base-image: ghcr.io/blue-build/base-images/fedora-silverblue-nvidia-open
image-version: latest # latest stable Fedora Silverblue (currently Fedora 44)
platforms:
  - linux/amd64

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    repos:
      copr:
        - lukenukem/asus-linux
        - pgaskin/looking-glass-client
    install:
      packages:
        - accerciser
        - gcc
        - clang
        - lld-devel
        - d-feet
        - distrobox
        - edk2-ovmf
        - libvirt
        - lld
        - llvm
        - python3-zombie-imp
        - qemu
        - qemu-kvm-core
        - rclone
        - virt-manager
        - zlib-devel
        - zlibrary-devel
        - perl
        - npm
        - vlc
        - asusctl
        - asusctl-rog-gui
        - supergfxctl
        - minicom
        - ksshaskpass
        - looking-glass-client
        - ffmpeg
        - webkit2gtk4.1-devel
    remove:
      auto-remove: false
      packages:
        - firefox
        - firefox-langpacks

  - type: default-flatpaks@v1
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
      remove:
        - org.gnome.eog
    user: {}

  - type: signing

  - type: script
    scripts:
      - verify-nvidia.sh
